name: Deployment pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build  application
      run: npm install 

    - name: Run the tests
      run: npm test    

    - uses: montudor/action-zip@v0.1.0
    - run: zip lambda.zip *

    - uses: stcalica/update-lambda@0.0.2
      with:
        package: lambda.zip
        function-name: github-training-function
        AWS_REGION: "us-east-2"
        AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}